url: https://github.com/WebPicArt/WebPicArt.github.io
baseurl: /WebPicArt.github.io/

# Site settings
logo: WebPicArt.github.io/img/logoPICART_100px.png
title: picArt
email: webpicart@gmail.com
description: "Una nuova Agenzia LabWeb-2.0-Agency Realizzazione siti web dinamici, responsive, professionali e moderni. ChatBot e Campagne Social Marketing "


# Team names, titles and social links

#- name: #Kay Garland
 # pic: #1
  #position: #Lead Designer
  #social:
   # - title: #twitter
    #  url: #
   # - title: #facebook
   #   url: #
   # - title: #stack-overflow
   #   url: #
people:
- name: Stefano UP
  pic: 6
  position: Web Master<br>Web Marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: dribbble #linkedin
      url: #

- name: Tiziano WoW
  pic: 5
  position: Graphic Designer<br>Video Maker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Renato Fucini
  - line: Rome, IT 00100

# Build settings
markdown: kramdown
permalink: pretty
