<<<<<<< HEAD
url: https://github.com/WebPicArt/WebPicArt.github.io
baseurl: /WebPicArt.github.io/

 # Site settings
logo: WebPicArt.github.io/img/logoPICART_100px.png
title: WebPicArt
email: webpicart@gmail.com
description: "Una nuova Agenzia LabWeb-2.0-Agency Realizzazione siti web dinamici, responsive, professionali e moderni. ChatBot e Campagne Social Marketing "


# Team names, titles and social links
=======
url: https://tryandfork.github.io/PicArt.github.io
baseurl: /PicArt.github.io/

# Site settings
title: PicArt
email: stefano.pica73@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: #Kay Garland
  pic: #1
  position: #Lead Designer
  social:
    - title: #twitter
      url: #
    - title: #facebook
      url: #
    - title: #stack-overflow
      url: #
>>>>>>> PicArt-it/gh-pages

#- name: #Kay Garland
 # pic: #1
  #position: #Lead Designer
  #social:
   # - title: #twitter
    #  url: #
   # - title: #facebook
   #   url: #
   # - title: #stack-overflow
   #   url: #
people:
- name: Stefano UP
  pic: 6
  position: Web Master<br>Web Marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: dribbble #linkedin
      url: #

- name: Tiziano WoW
  pic: 5
  position: Graphic Designer<br>Video Maker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: website #dribbble#google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
<<<<<<< HEAD
  - line: Renato Fucini
  - line: Rome, IT 00100
=======
  - line: Via Renato
  - line: Roma 00137 Italy
>>>>>>> PicArt-it/gh-pages

# Build settings
markdown: kramdown
permalink: pretty
